### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Fwatermelon** [SatCom-TELMA/MA-DRL_Routing_Simulator#4]
I am experiencing an issue where my 64GB of RAM is completely used up when running 5 satellites. Could you please share your computer configuration? Additionally, do you have any recommendations on how to handle this memory issue?
Thank you！

**Comment by Fedeloz** [comment]
Hi, I assume that you meant 5 Gateways here, instead of 5 satellites:
#"when running 5 satellites"

**Recomendations for reducing RAM usage:**

1. **Decrease the traffic fraction.**  The traffic fraction can be changed in "inputRL.csv":

`Locations,Constellation,**Fraction**,Test type,Test length
Malaga,Kepler,**0.1**,Latency,1.00`

2. **Import pre-trained networks and deactivate the exploration.** This will make routing way more efficient.
3. Deactivating the online phase is recommended too, but it should work with 64GB doing the mentioned above.

I have pushed a version that you should be able to run. In this version, the simulator is configured to run with 5 Gateways, 10% of the traffic, online phase, importing some pre-trained neural networks and no movement of the constellation during 2 seconds.

Try pulling the latest commit:
** 2d3f00c**

And running: 
`python SimulationRL.py`

I usually use a supercomputer when I train the network with >5 Gateways (https://www.scbi.uma.es/web/es/inicio/), this process is very RAM hungry. The most consuming event is training from scratch with exploration.

PD: I try to optimize the RAM usage when not doing technical research or reading papers, but I am not a sw developer. I am open for any recommendations to optimize the RAM usage with Keras.

**Comment by Fwatermelon** [comment]
I encountered an issue where, when the satellite's buffer queue is full, earlier-arriving packets are not discarded. This leads to an effectively infinite buffer and few packet drops, which doesn’t reflect real-world behavior. How can I modify the code to implement a fixed buffer size to allow for proper packet drop rate calculation?

Thank you for your help.
