### ISSUE TITLE
Relationship Between 'Fraction' Parameter and Network Traffic

### ISSUE THREAD

**Issue by refealwang** [SatCom-TELMA/MA-DRL_Routing_Simulator#5]
Hello author, I understand that the parameter 'fraction' can control the network traffic size. Could you please clarify the relationship between the 'fraction' parameter and the actual network load? For example, if I set 6 ground stations as active and use fraction = 0.1, how can I calculate the Traffic generation rate (Kbps)/average link traffic (Mbps)?

**Comment by refealwang** [comment]
If you're interested in discussing this with me, feel free to contact me via my email: refeal_wang_huat@foxmail.com

**Comment by Fedeloz** [comment]
Hi. The traffic generated by gateways is detailed in the full paper [preprint](https://arxiv.org/pdf/2405.12308) and the simulator [paper](https://zenodo.org/records/13885645). 
Basically each gateway sends traffic to each other gateway equally, meaning that adding more gateways will increase the total traffic generated by each gateway since there are more sources of data packets. **'fraction'** indeed controls the traffic injected by gateways just by multiplying the total number of packets generated by this factor.

The total number of packets generated by each gateway is printed by the console before every simulation starts, for example with 2 active gateways ( Milliard is 10e9. ):

> ----------------------------------
> Traffic generated per GT (totalAvgFlow per Milliard):
> ----------------------------------
> Malaga, Spain: 2.103214
> Los Angeles, California, US: 1.8516475
> ----------------------------------

There is not such way to control the traffic in terms of Mbps or related. However, the average throughput is plotted after each simulation:

`plotAllThro = True      # If True, it plots throughput plots for each single path between gateways. If False, it plots a single figure for overall Throughput
`

Keep this parameter to True to see the average throughput per source-destination pair in the uplink and the downlink for that source-destination pair. Otherwise the average uplink and downlink throughput is plotted only.

I just pushed a stable version where this feature in implemented (See c0976e9), in case your pull did not have this since it is a recent feature.

**Comment by refealwang** [comment]
Thank you for your response. I have encountered another issue. When all other conditions remain the same (pathing = pathings[0]/pathings[3]), I modified only the Fraction size and observed a strange phenomenon: a decrease in Fraction significantly increases the queuing delay, as shown in the figure below.
![图片1](https://github.com/user-attachments/assets/d970e789-3899-4b6d-8b1c-87673d5303e1)
![图片2](https://github.com/user-attachments/assets/bbe41a0e-f2f4-42b9-9f54-7b1dcda80e06)

In my understanding, as the number of packets increases, the queuing delay should also increase, rather than decrease. Is there something wrong with my understanding?
